### PR TITLE
the blogs with empty blog image and title are removed

### PR DESCRIPTION
**Pull request by vishnubansal001**
## Related Issue
In the previous version the blog posts with having no title and the image are being shown but now thet are removed

## Description of Changes
The blogs posts without having any of the information like about text , heading , Image regarding the blog post and being rendered but now each and every post is first checked that it have at least that so that it can rendered and shown easily to the user using a simple vanila javascript  

## Checklist:

- [ yes] I am a GSSOC'23 contributor
- [yes ] I have conducted a self-review of my code.
- [ yes] I have included comments in areas that may be difficult to understand.
- [ yes] I have made corresponding updates to the project documentation.
- [ yes] My changes have not introduced any new warnings.

## Screenshots
Previous version:
Screenshot (103)

New version:
Screenshot (110)

### CODE REVIEW

**Comment by AKD-01** [comment]
I removed it from the database. :)

**Comment by vishnubansal001** [comment]
The added lines also checks from the coming data that whether the blog having that part or not and the check is a good thing according to me..
Also please merge my pull request as this will be my first contribution on the gssoc please

**Comment by vishnubansal001** [comment]
Also if you fetch the data from some of the datasets that are initially defined and the data set which are not clean like this one will have a bad impact on the user so thats why i think a check is necessary

**Comment by AKD-01** [comment]
Hey, I will review all the prs on Wednesday now. Please wait till then.

**Pull request closed without merging**
