### PR TITLE
preloadder added

### PR DESCRIPTION
**Pull request by Prap1**
#150 i am added preloadder

### CODE REVIEW

**Comment by AKD-01** [comment]
your preloader is not aligned in the center, please make sure it remains in the center always

**Comment by AKD-01** [comment]
please resolve all the conflicts

**Comment by AKD-01** [comment]
Please resolve all the conflicts and as soon as you do that please tag me on the github with your pr link. Thank you

**Comment by Prap1** [comment]
> Please resolve all the conflicts and as soon as you do that please tag me on the discord (BlogWeet) with your pr link. Thank you

can you tell me your discord id or name.

**Comment by AKD-01** [comment]
Please dont do changes on your own unless its regarding your issue that you have raised, your code changes have made the mobile version to look like this
image
You have removed the PageNotFound page and Contact us page routes.

**Comment by Prap1** [comment]
> Please dont do changes on your own unless its regarding your issue that you have raised, your code changes have made the mobile version to look like this image You have removed the PageNotFound page and Contact us page routes.

I am not add anything except preloadder it's automatically come in my code

**Comment by AKD-01** [comment]
Because of no updates from your side for more than 2 weeks, closing the pr.

**Pull request closed without merging**
