### PR TITLE
Avoid Blank Posts and Add Default Photo #50

### PR DESCRIPTION
**Pull request by rt-001**
**No Title No Post**

Screenshot 2023-05-21 at 6 59 21 PM

**No Post**

Screenshot 2023-05-21 at 6 59 32 PM

**No Title**

Screenshot 2023-05-21 at 6 59 44 PM

### CODE REVIEW

**Comment by AKD-01** [comment]
@rt-001 where is default photo added?

**Comment by AKD-01** [comment]
Because of no respone from your side for more than 2 weeks, closed the pr.

**Comment by rt-001** [comment]
> @rt-001 where is default photo added?

@AKD-01   I  did it in the last PR, but you mentioned that this reduces the user experience. I apologize for not replying earlier, but I completed my work.

**Comment by AKD-01** [comment]
Ohhk, if you have completed your work, you may raise a new pr.

**Pull request closed without merging**
