### PR TITLE
made changes in the blog section

### LINKED ISSUE #106: UI of blogs in Blogweet
Hey @AKD-01, as a part of GSSOC'23, I would like to change the UI of blogs by improving the fonts as well as text content styling properties. Kindly assign me the issue.

### PR DESCRIPTION
**Pull request by shruti8302**
Closes #106 

Screenshot (398)
Screenshot (399)

### CODE REVIEW

**Comment by AKD-01** [comment]
Would you please look into this and change the size of that background color to make it look more attractive.
https://blogweet.vercel.app/hhh-rrr/ycn6Am43GHRf5IiGVtsn

**Comment by shruti8302** [comment]
I have removed that background color on hover. I tried to apply other background colors but they didn't suit with the styling of the blogs so I have applied another property in which if we will hover on share button, it's size will will increase.

**Comment by shruti8302** [comment]
Also, could u please add relevant tags in the issue so that it can be considered for the evaluation of scores in GSSOC'23.

**Comment by shruti8302** [comment]
issue #106

**Comment by shruti8302** [comment]
@srivastavaritik review it please

**Pull request merged**
