### PR TITLE
#187 Add Notification Section

### PR DESCRIPTION
**Pull request by Ayushhgupta39**
image

Added notification section to the website, which renders the latest notification of all the new posts. Please verify this and merge under GSSoC'23.

### CODE REVIEW

**Comment by AKD-01** [comment]
Remove conflicts and errors

**Comment by Ayushhgupta39** [comment]
> Remove conflicts and errors
Check now

**Comment by Ayushhgupta39** [comment]
> Remove conflicts and errors

Check now

**Comment by AKD-01** [comment]
There are still some errors.I would love to have a notification section. So please look into the errors and try to resolve it. Also mention your issue no as i have to add the labels. thank you
image

**Comment by Ayushhgupta39** [comment]
I tried to check the details on vercel, but it showed nothing.
image

I guess this one may not be from my end, and as this does not have any other conflicts or errors, it should be good to merge. Let me know if there is anything else I can check out.

**Comment by AKD-01** [comment]
image
please correct this error

**Comment by AKD-01** [comment]
Resolve Conflicts, tag on discord with pr link.

**Comment by Ayushhgupta39** [comment]
I need some time, Will definitely resolve them. I'm currently out of town

**Comment by AKD-01** [comment]
@Ayushhgupta39 No problem. When conflicts are resolved tag me on discord with pr link.

**Comment by AKD-01** [comment]
closed as not resolved from long time

**Pull request closed without merging**
