### PR TITLE
Responsive CREATE BLOG page

### PR DESCRIPTION
**Pull request by marshadkhn**
**Issue number - #166**
Hey @AKD-01, I solved the responsive create blog post in this project

This pull request contains following changes
1. Responsive create width all width possible
2. Had a image folder (please delete that, not used)

Branch name - marshadkhn
Merge my code

### CODE REVIEW

**Comment by AKD-01** [comment]
Please update your pr from main branch

**Comment by AKD-01** [comment]
image

**Comment by marshadkhn** [comment]
@AKD-01 @srivastavaritik 
Still waiting for merging

**Comment by marshadkhn** [comment]
@AKD-01 @srivastavaritik

**Pull request closed without merging**
