### PR TITLE
Add form validation using Yup for creating posts

### PR DESCRIPTION
**Pull request by Mudassirkhan2**
#39  I implemented form validation using the Yup library for the Create post form submission. The form now includes validation rules for the input fields to ensure the entered data meets the required criteria.

issue Solved :  #39 

Integrated Yup library for form validation
Created a validation schema using Yup to define rules for each input field
Added error messages to display validation errors for each field
Configured form submission to only proceed if all validation rules are met
Updated the form component to utilize the Yup validation schema

Before 
Screenshot 2023-05-20 093957

After : 
Screenshot 2023-05-21 142651

### CODE REVIEW

**Comment by Mudassirkhan2** [comment]
@AKD-01

**Comment by AKD-01** [comment]
please resolve the conflicts and tag me

**Comment by Mudassirkhan2** [comment]
@AKD-01 
resolved merge conflicts

**Comment by AKD-01** [comment]
@Mudassirkhan2 image preview is not working, please rectify it

**Comment by Mudassirkhan2** [comment]
can i know what you you are trying to say @AKD-01  ?

**Comment by AKD-01** [comment]
image
This image preview ain't working and also please resolve all the conflicts first.

**Comment by AKD-01** [comment]
Closing this issue as no response from your end. And now, there is create post form validation on the blogweet.

**Pull request closed without merging**
