### PR TITLE
[Request] Contact Us Page UI improvement

### PR DESCRIPTION
**Pull request by Rishav1707**
## Related Issue

Closes: #250 

## Description of Changes

- Add `box-shadow` CSS properties to the input element and button.
- Add `transition property` to the button element.
- Change the background colour of the button element.
- Change the hover effect background color of the button element.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| image | image |

### CODE REVIEW

**Comment by AKD-01** [comment]
There are errors in Home.css file. Resolve them.

**Comment by Rishav1707** [comment]
> There are errors in Home.css file. Resolve them. @Rishav1707

Websites are not running locally. It's showing the following error.

image

**Comment by AKD-01** [comment]
@Rishav1707 please check readme.md again.

**Comment by AKD-01** [comment]
Closing as errors not resolved yet. Please create another pr after doing the changes.

**Pull request closed without merging**
