### PR TITLE
Improved Website Design

### PR DESCRIPTION
**Pull request by iamRabia-N**
This PR contain updated web design code. However, if you want some changes, do let me know. I would love to consider it. 

Here is the sneak peek of updated design:

blogweet pic

### CODE REVIEW

**Comment by AKD-01** [comment]
please raise an issue first

**Comment by iamRabia-N** [comment]
Hi @AKD-01 !
I had first created the issue as:
###  Website's Design Improvement #53

The issue was also accepted.

pic

**Comment by iamRabia-N** [comment]
You just didn't add label at that time

**Comment by iamRabia-N** [comment]
> Hi @AKD-01 ! I had first created the issue as:
> 
> ### Website's Design Improvement #53
> The issue was also accepted.
> 
> pic

@AKD-01

**Pull request closed without merging**
