### PR TITLE
Solved issue #198 : Fixed multiple toast display

### PR DESCRIPTION
**Pull request by rayyan016**
Title: Fixed multiple toast display

Description
This PR addresses the issue #198 

Changes made : .\src\pages\Home.js
Changed position of <ToastContainer> to put it outside of inner <div>. This prevents multiple renders of <ToastContainer>.

Before: 

Blogweet issue2

After:

blogweet pr2

@AKD-01 Please let me know if you would like any changes.

### CODE REVIEW

**Comment by AKD-01** [comment]
@rayyan016 please raise another pr with same changes as due to some errors in the website your code has been reverted

**Comment by rayyan016** [comment]
No problem. I will. 🫡

**Comment by rayyan016** [comment]
It is done. You can find it [here](#251 )

**Comment by rayyan016** [comment]
You can find it [here](https://github.com/AKD-01/blogweet/pull/251)

**Pull request merged**
