### PR TITLE
Enhanced the About page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Before
Screenshot 2023-05-27 at 8 45 33 AM

After
Screenshot 2023-05-27 at 8 45 25 AM

This pr links to the issue #33

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@AKD-01 Please check the pr

**Comment by AKD-01** [comment]
Please resolve the conflicts.

**Comment by karthiknadar1204** [comment]
How do i do that

**Comment by karthiknadar1204** [comment]
@AKD-01 ?

**Comment by karthiknadar1204** [comment]
@AKD-01 Will rework this issue and push the changes again, please check the pr tomorrow again.
Merging coinciding pr's causes this kind of conflicts

**Comment by AKD-01** [comment]
please resolve the conflicts again and make the page responsive as well.

**Comment by karthiknadar1204** [comment]
fine

**Comment by AKD-01** [comment]
Since, you raised new pr closing this one.

**Pull request closed without merging**
