### PR TITLE
Added the edit option for the user

### PR DESCRIPTION
**Pull request by Akanksha-202**
image
image
image

Now the user can edit the submitted post content and it will reflect automatically over the website :)
This is regarding the issue #23 
kindly review the PR and suggest if more changes are req for the same.

### CODE REVIEW

**Comment by iamRabia-N** [comment]
Hi @Akanksha-202!
Can you tell me how you set this repo in local environment? I am facing errors while setting it in local environment. I would appreciate your response.

**Comment by Akanksha-202** [comment]
> Hi @Akanksha-202!
> Can you tell me how you set this repo in local environment? I am facing errors while setting it in local environment. I would appreciate your response.


Fork the repo -> Clone it -> add upstream of main repo -> create branch 
And start doing the changes!

Can be reflected over localhost:3000 via npm start !

Detailed steps are mentioned in the readme section as well .

Hope this helps :)

**Comment by iamRabia-N** [comment]
Thank you for your response. I am facing errors in npm start command.

**Comment by Akanksha-202** [comment]
Do npm install first in the folder and then npm start

**Comment by AKD-01** [comment]
hi @Akanksha-202 , I appreciate your effort in making this, but I suggest you make a modal for editing content and use a textarea so that the user can see all the content at once.

**Comment by Akanksha-202** [comment]
Sure!
Will reverse soon with these changes

**Comment by AKD-01** [comment]
> @AKD-01 do you want the user to have a textarea within a div and a separate box to appear? And they have to write the whole updated content there
> 
> Or do you want the user to see their submitted content and there they can alter some of their content

Hi @Akanksha-202 , can you just implement both the things that you have mentioned and give the option to users to choose what they want to do i.e. to edit their content or upload new content

**Comment by Akanksha-202** [comment]
@AKD-01 i have closed this PR, will create new PR with all changes
But because I'm dealing with firebase content in order to retrieve while letting the user to alter the content, I realised that you have not created env file for it, so because of my changes the content of already existing posts are not there now,
Kindly update that and from now I'll be dealing in my firebase (with mu APIs).
Kindly protect your credentials for not letting this happen in future!

**Pull request closed without merging**
