### PR TITLE
Added Featured Post section and written some posts on web3 and ai #172

### PR DESCRIPTION
**Pull request by ombhojane**
Issue #172
Hey, I've created a Featured Post Page and added some posts.
In this process, I found that, there is a need of Feature Post section in Sidebar. I'll create another PR to create a feature post section on sidebar to easily access posts and updates from officials.
Thank you for assigning this issue to me..

Preview:
image

### CODE REVIEW

**Comment by ombhojane** [comment]
Hey, how can I merge this issue?

**Review by ombhojane — COMMENTED** [review]
Hey, I have created Featured Post Section and added some posts

**Review by ombhojane — COMMENTED** [review]
Hey, I've created featured posy section and added some posts.
Please review and let me know for any changes, hoping for receiving my 1st PR getting merged...
GSSOC'23 :)

**Comment by ombhojane** [comment]
Hey @AKD-01 , sorry for tagging, but I didn't get any response.
Please review the changes for PR

**Comment by AKD-01** [comment]
I will review all the prs on Saturday, please wait till then.

**Comment by AKD-01** [comment]
hi @ombhojane , as I can see you have written your code in HTML but this repo is fully made in react, please convert it in react

**Comment by AKD-01** [comment]
Hey, where are your changes, I can't see that on deployment? Could you please guide me?
image

As i can't see the featured post section anywhere in the deployment.

**Comment by AKD-01** [comment]
Because of no respone from your side for more than 2 weeks, closing the pr.

**Pull request closed without merging**
