### PR TITLE
feat: add image optimization feature

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Related Issue
Optimizing the image assets which was consuming so much of bandwidth and delays the page load times

Closes: #269

## Description of Changes

- This pull request is done for optimizing the size of `jpg` images, we done this by converting those `jpg` & `jpeg` to `webp` format.
-  As per our goal every `jpg` image is compressed, so average image size is now lesser than `300kb` before it was more than `2mb`.
-  Reduced more than `80%` of image size with the help of `webp` compression (`webp` is also supported on all modern browsers)
- And along with i updated the source code (`js` scripts) which includes the image source path to ensure the proper working of application after optimizing those assets
- For Blog post `src={${'https://images.weserv.nl/?output=webp&url='}${post.image}}` webp compression
- For Home page ` src={${'https://images.weserv.nl/?output=webp&width=150px&url='}${post.image}}` we minimized it's size also because an average image width is more then 1500px but in this section we only use `8rem` of its width
- The api used here is absolutely free and blazingly fast also so we don't wanna worry about the latencies!
> This issue is assigned to me under GSSOC2023. The issue number is #269  

For example:
- Before optimization an average size of an image is more than `2mb` now after webp api integration in size lesser than `200kb`
- In the below screenshot i only added the preview of `Home.js`, because we can visually see those changes in sizes but the images in `Blogpost.js` will not scaled down but their size will be compressed

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Screenshot_2023-05-28-13-14-44_1366x768 | Screenshot_2023-05-28-13-17-21_1366x768 |

## Reviewer
- @AKD-01

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Bro @srivastavaritik, Please make sure to merge this PR.
This is opened before 2 weeks still not received a single response from PA, I hope you can understand.

Thanks!

**Comment by AKD-01** [comment]
Hi @0xabdulkhalid , your concern about image optimisation i fine but this cahnge will affect the gifs, they will become a simple image
Before: https://blogweet-ivndmnyty-akd-01.vercel.app/user/ANJALI-DUBEY/3xt8o2BTDkWYhQJAMaZO
After: https://blogweet-2oy6q7mtk-akd-01.vercel.app/user/ANJALI-DUBEY/3xt8o2BTDkWYhQJAMaZO
have a look

**Comment by 0xabdulkhalid** [comment]
Yeah @AKD-01, you're right.

Our goal is to improve page performance by minimizing the asset's size. In fact we don't wanna add `gifs` in upcoming blogs.

If we want to include fancy `gifs` then the site's SEO will be drastically affected, As a developer we want to make effecient move which makes our app to perform well in all aspects.

Now it's your choice in terms of considering the SEO and page performance, Remember they both are crucial in terms of building a scalable site.

**Comment by 0xabdulkhalid** [comment]
Can i get any update regarding this PR @AKD-01 & @srivastavaritik ?

**Comment by AKD-01** [comment]
We would like to keep the options of gifs, in future may be we will see how can we optimise the site's performance.

**Pull request closed without merging**
