### PR TITLE
improved blog page and made it responsive

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Related Issue

Closes: #[issue number]
#33 

## Description of Changes
Added a container to the elements in the blog page and beautified the text within with some html tags

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
Improved
Screenshot 2023-05-28 at 6 01 33 PM

Screenshot 2023-05-28 at 6 01 51 PM

Old

Screenshot 2023-05-28 at 6 03 58 PM

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@AKD-01 Done

**Comment by karthiknadar1204** [comment]
subset of #247

**Comment by srivastavaritik** [comment]
Hey @karthiknadar1204 , the card is not aligned properly 
image
correct this and raise another pr with some more changes. I am closing this for now.

**Comment by karthiknadar1204** [comment]
Ok so the overall design is fine right, i think it was perfectly responsive as well.

The main thing to be done is to position it correctly,right?

Please add any other changes that need to be added so that i can resolve it at once in the next pr @srivastavaritik @AKD-01

**Comment by karthiknadar1204** [comment]
As for some more changes,please suggest the changes you want me to apply, will get it done sure thing

**Pull request closed without merging**
