### PR TITLE
#186 #188 Updated Sign in buttons and added Favicon

### PR DESCRIPTION
**Pull request by Ayushhgupta39**
image
image

I updated the Sign-in buttons and added the new favicon, these new buttons are more original and professional. They work perfectly and maintain the structure of the code. Please verify this and merge and under GSSoC'23.

### CODE REVIEW

**Comment by AKD-01** [comment]
image
no icons are visible, you were not supposed to remove them

**Comment by Ayushhgupta39** [comment]
> image no icons are visible, you were not supposed to remove them

I didn't removed them on purpose, let me fix this

**Comment by Ayushhgupta39** [comment]
> image no icons are visible, you were not supposed to remove them

Fixed this

**Comment by AKD-01** [comment]
PLEASE RESOLVE THE CONFLICTS. AND DON'T REMOVE THAT TWITTER ICON.
image

Also did you worked on Notification section too? As i can see that in your deployment.

**Comment by AKD-01** [comment]
@Ayushhgupta39 please respond, otherwise I will close the pr on saturday.

**Comment by Ayushhgupta39** [comment]
I'm out of town now, please try to remain more active.

**Comment by AKD-01** [comment]
It's you, who didn't reply while i was active. Neverthless You may raise new pr when you're back in that way there will be no conflicts.

**Pull request closed without merging**
