### PR TITLE
comment and like button added for blog

### PR DESCRIPTION
**Pull request by Prap1**
#190 

iam complete the fully functional like button and comment, when Anyone click on like button like is increase and when person click on unlike like willbe decrese and also adding comment section where person add comment and its show in the post

### CODE REVIEW

**Comment by AKD-01** [comment]
resolve all the conflicts, and also please enhance UI

**Comment by AKD-01** [comment]
Please resolve all the conflicts and tag me on discord as soon as you do that. Thank you!

**Comment by Prap1** [comment]
> Please resolve all the conflicts and tag me on discord as soon as you do that. Thank you!

please share your discord id or name, so i can connect with you.

**Comment by srivastavaritik** [comment]
please resolve all the conflicts and make proposed changes and raise a new pr

**Pull request closed without merging**
