### PR TITLE
Improved login page

### PR DESCRIPTION
**Pull request by KeyurGK**
Issue #40 
Improvements made :
1) Aligned the button content with proper margins and padding.
2) Both the buttons are aligned in line with the title.
3) Added a simple border to the page.
4) Edited the title content to 'Login into Blogweet'
image

### CODE REVIEW

**Comment by AKD-01** [comment]
hi @KeyurGK

**Comment by KeyurGK** [comment]
@AKD-01 
Changes made as advised :
1)Removed the border.
2)Edited back to the original title content.

**Comment by KeyurGK** [comment]
@AKD-01 Changes made as advised!

**Comment by AKD-01** [comment]
Have you checked the deployment?
image

It is showing something like this.

**Pull request closed without merging**
